spring:
  profiles:
    active: local # 로컬 환경에서만 사용
  datasource:
    hikari: # HikariCP가 수동 설정을 하더라도 인식할 수 있도록
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:tcp://localhost/~/test
      username: sa
      password:
server:
  ssl: # HTTPS 설정
    key-store: keystore.p12
    key-store-type: PKCS12
    key-store-password: authtest
    key-alias: spring
    enabled: true
  port: 8443
  http2:
    enabled: true # HTTP2 활성화 - JDK 9 version 이상 필요
